---
## YAML based inventory, see:
## https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
swift:
  children:
    swift_admin:
      hosts:
#        swift-admin:
        swift-01:
    swift_proxy:
      hosts:
        swift-[01:03]:
    swift_account:
      hosts:
        swift-[01:03]:
    swift_container:
      hosts:
        swift-[01:03]:
    swift_object:
      hosts:
        swift-[01:03]:
  hosts:
#    swift-admin:
#      server_ip: 10
#      virt_infra_disk_size: 40
#      virt_infra_disks:
#        - name: "boot"
#          clone: true
    swift-01:
      server_ip: 11
      swift_vips:
        - 111
        - 112
        - 113
    swift-02:
      server_ip: 12
      swift_vips:
        - 112
        - 113
        - 111
    swift-03:
      server_ip: 13
      swift_vips:
        - 113
        - 111
        - 112
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
    ## Networks must be defined here so that each host gets it set as a var, in order to dereference ip
    swift_outward_subnet: 203.0.113.0/24
    swift_cluster_subnet: 192.0.2.0/24
    swift_replication_subnet: 198.51.100.0/24
    swift_outward_ip: "{{ swift_outward_subnet | next_nth_usable(server_ip) }}"
    swift_cluster_ip: "{{ swift_cluster_subnet | next_nth_usable(server_ip) }}"
    swift_replication_ip: "{{ swift_replication_subnet | next_nth_usable(server_ip) }}"
    swift_account_rings_min_part_hours: 0
    swift_container_rings_min_part_hours: 0
    swift_object_rings_min_part_hours: 0

    swift_account_rings:
      account:
        backup: true
        min_part_hours: 0
        part_power: 10
        replicas: 3

    swift_container_rings:
      container:
        backup: true
        min_part_hours: 0
        part_power: 10
        replicas: 3

    swift_object_rings:
      object:
        # ring builder vars
        backup: true
        create: true
        min_part_hours: 0
        part_power: 17
        path: /etc/swift
        replicas: 3
        # swift.conf vars
        aliases:
          - replicas-3
          - gold
        default: true
        diskfile_module: egg:swift#replication.fs
        policy_type: replication
      object-1:
        # ring builder vars
        backup: true
        create: true
        min_part_hours: 0
        part_power: 17
        path: /etc/swift
        # For EC, replicas must equal the total of data and parity fragments
        replicas: 7
        # swift.conf vars
        aliases:
          - ec-43
          - silver
        policy_type: erasure_coding
        ec_type: liberasurecode_rs_vand
        ec_num_data_fragments: 4
        ec_num_parity_fragments: 3
        ec_object_segment_size: 1048576
        diskfile_module: egg:swift#erasure_coding.fs

    swift_devices:
      0:
        #disk: /dev/data_nvme0n1/data_nvme0n1_lv
        disk: /dev/nvme0n1
        ip: "{{ hostvars['swift-01'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          account:
            weight: 100
            port: "{{ swift_account_port }}"
          container:
            weight: 100
            port: "{{ swift_container_port }}"
      1:
        #disk: /dev/data_nvme0n1/data_nvme0n1_lv
        disk: /dev/nvme0n1
        ip: "{{ hostvars['swift-02'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          account:
            weight: 100
            port: "{{ swift_account_port }}"
          container:
            weight: 100
            port: "{{ swift_container_port }}"
      2:
        #disk: /dev/data_nvme0n1/data_nvme0n1_lv
        disk: /dev/nvme0n1
        ip: "{{ hostvars['swift-03'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          account:
            weight: 100
            port: "{{ swift_account_port }}"
          container:
            weight: 100
            port: "{{ swift_container_port }}"
      3:
        #disk: /dev/data_sdb/data_sdb_lv
        disk: /dev/sdb
        ip: "{{ hostvars['swift-01'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        mount_options:
          - nofail
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      4:
        #disk: /dev/data_sdb/data_sdb_lv
        disk: /dev/sdb
        ip: "{{ hostvars['swift-02'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      5:
        #disk: /dev/data_sdb/data_sdb_lv
        disk: /dev/sdb
        ip: "{{ hostvars['swift-03'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      6:
        #disk: /dev/data_sdc/data_sdc_lv
        disk: /dev/sdc
        ip: "{{ hostvars['swift-01'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        mount_options:
          - nofail
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      7:
        #disk: /dev/data_sdc/data_sdc_lv
        disk: /dev/sdc
        ip: "{{ hostvars['swift-02'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      8:
        #disk: /dev/data_sdc/data_sdc_lv
        disk: /dev/sdc
        ip: "{{ hostvars['swift-03'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      9:
        #disk: /dev/data_sdd/data_sdd_lv
        disk: /dev/sdd
        ip: "{{ hostvars['swift-01'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        mount_options:
          - nofail
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      10:
        #disk: /dev/data_sdd/data_sdd_lv
        disk: /dev/sdd
        ip: "{{ hostvars['swift-02'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"
      11:
        #disk: /dev/data_sdd/data_sdd_lv
        disk: /dev/sdd
        ip: "{{ hostvars['swift-03'].swift_cluster_ip }}"
        region: 1
        zone: 1
        meta: 'meta'
        rings:
          object:
            weight: 100
            port: "{{ swift_object_port }}"
          object-1:
            weight: 100
            port: "{{ swift_object_port }}"

    virt_infra_autostart: no
    virt_infra_network_config: true
    virt_infra_cpus: 2
    virt_infra_cpus_max: 4
    virt_infra_ram: 2048
    virt_infra_ram_max: 4096
    virt_infra_variant: centos-stream8
    virt_infra_distro_image: CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2
    virt_infra_distro_image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2
    virt_infra_distro_image_checksum_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CHECKSUM
    virt_infra_guest_deps: []
    virt_infra_disk_cmd:
      - echo 'fastestmirror=1' >> /etc/dnf/dnf.conf
      - rm -f /etc/sysconfig/network-scripts/ifcfg-e*
      - echo "net.ipv6.conf.all.disable_ipv6 = 1" > /etc/sysctl.d/70-ipv6.conf
      - echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.d/70-ipv6.conf
    virt_infra_networks:
      - name: "swift-outward"
        type: nat
        device: eth0
        addresses:
          - "{{ swift_outward_ip }}/{{ swift_outward_subnet | ipaddr('prefix') }}"
        gateway4: "{{ swift_outward_subnet | ipaddr('next_usable') }}"
        nameservers:
          search:
            - swift.local
          addresses:
            - "{{ swift_outward_subnet | ipaddr('next_usable') }}"
        dhcp6: false
      - name: "swift-cluster"
        type: nat
        device: eth1
        addresses:
          - "{{ swift_cluster_ip }}/{{ swift_cluster_subnet | ipaddr('prefix') }}"
        dhcp6: false
      - name: "swift-replication"
        type: nat
        addresses:
          - "{{ swift_replication_ip }}/{{ swift_replication_subnet | ipaddr('prefix') }}"
        dhcp6: false
        device: eth2
    virt_infra_disk_size: 40
    virt_infra_disks:
      - name: "boot"
        clone: true
        ssd: "true"
      - name: "data-scsi-03"
      - name: "data-scsi-02"
      - name: "data-scsi-01"
      - name: "data-nvme-01"
        bus: "nvme"
